#!/bin/sh -e

export DESTDIR="$1"

meson \
        --prefix=/usr \
        -Dexamples=false \
	-Dwerror=false \
	-Db_ndebug=true \
        . build

ninja -C build
ninja -C build install

rm -rf "$1/usr/share/zsh/"
rm -rf "$1/usr/share/wayland-sessions/"
rm -rf "$1/usr/share/fish/"
rm -rf "$1/usr/share/bash-completion/"



cat <<EOF

### IMPORTANT ###
### IMPORTANT ###

For rootless sway, wlroots is compiled with libcap.
Your user has to be in the video group.

addgroup USERNAME video

### IMPORTANT ###
### IMPORTANT ###
EOF
