#!/bin/sh -e

#GCC10 fix
export CFLAGS="$CFLAGS -fcommon"

export DESTDIR="$1"

meson \
	--prefix=/usr \
	--buildtype=plain \
	-Dexamples=false \
        -Dlibcap=disabled \
        -Dlogind=disabled \
        -Dxcb-errors=disabled \
        -Dxcb-icccm=disabled \
        -Dxcb-xkb=disabled \
        -Dxwayland=disabled \
        -Dx11-backend=disabled \
	-Dfreerdp=disabled \
	. build

ninja -C build
ninja -C build install
