#!/bin/sh -e

#GCC10 fix
export CFLAGS="$CFLAGS -fcommon"

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=plain \
    -Dexamples=false \
    . build

ninja -C build
ninja -C build install

rm -rf "$1/usr/share/zsh/"
rm -rf "$1/usr/share/wayland-sessions/"
rm -rf "$1/usr/share/fish/"
rm -rf "$1/usr/share/bash-completion/"
